# Generated by Django 5.0.1 on 2026-04-21 17:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chamas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("premium", "Premium"),
                            ("claim_payout", "Claim Payout"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound (C2B)"),
                            ("outbound", "Outbound (B2C)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("mpesa_ref", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chama_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chamas.chama",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-initiated_at"],
            },
        ),
    ]
