# Generated by Django 5.0.1 on 2026-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
