# Generated by Django 5.x on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mpesa_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
