# Generated by Django 5.0.1 on 2026-04-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_hash",
        ),
    ]
