# Generated by Django 5.0.1 on 2026-05-27 14:00
# Migration to remove GCP Document AI related fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_password_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kyc_document_url",
        ),
    ]
