# Generated by Django 5.0.1 on 2026-05-31 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_gcp_kyc_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("flagged", "Flagged"),
                    ("review", "Needs Review"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("claims_officer", "Claims Officer"),
                    ("chama_admin", "Chama Admin"),
                    ("chama_member", "Chama Member"),
                    ("individual", "Individual"),
                ],
                default="individual",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("passport", "Passport"),
                            ("drivers_license", "Driver's License"),
                        ],
                        default="national_id",
                        max_length=30,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        help_text="Uploaded KYC document file",
                        upload_to="kyc-documents/%Y/%m/%d/",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        help_text="Azure Blob Storage URL after upload",
                        null=True,
                    ),
                ),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Upload"),
                            ("uploaded", "Uploaded to Storage"),
                            ("analyzed", "Analysis Complete"),
                            ("failed", "Upload/Analysis Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "analysis_result",
                    models.JSONField(
                        blank=True,
                        help_text="Complete analysis result from Azure Document Intelligence",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_kyc_document",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_kyc_d_user_id_21393a_idx",
                    ),
                    models.Index(
                        fields=["upload_status"], name="users_kyc_d_upload__fd55da_idx"
                    ),
                ],
            },
        ),
    ]
