# Generated by Django 5.0.1 on 2026-04-21 17:04

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                (
                    "plan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_name", models.CharField(max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("family", "Family"),
                            ("group", "Group"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "coverage_category",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("life", "Life"),
                            ("accident", "Accident"),
                            ("property", "Property"),
                            ("income_protection", "Income Protection"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "min_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("max_coverage", models.DecimalField(decimal_places=2, max_digits=12)),
                ("duration_days", models.IntegerField()),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "plans_insuranceplan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "policy_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "coverage_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "premium_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("payment_reference", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("lapsed", "Lapsed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("blockchain_hash", models.CharField(blank=True, max_length=66)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "plans_policy",
                "ordering": ["-created_at"],
            },
        ),
    ]
