# Generated by Django 5.0.1 on 2026-04-21 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chamas", "0002_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="insuranceplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="chama_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies",
                to="chamas.chama",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="plan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="plans.insuranceplan"
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceplan",
            index=models.Index(
                fields=["status", "plan_type"], name="plans_insur_status_c3ff53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceplan",
            index=models.Index(
                fields=["coverage_category"], name="plans_insur_coverag_f27faf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["user_id", "status"], name="plans_polic_user_id_f8ea7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(fields=["status"], name="plans_polic_status_04cde3_idx"),
        ),
    ]
