# Generated by Django 5.0.1 on 2026-07-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_alter_insuranceplan_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="payment_reference",
            field=models.CharField(max_length=100),
        ),
    ]
