# Generated by Django 5.0.1 on 2026-04-21 17:04

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "claim_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("accident", "Accident"),
                            ("death", "Death"),
                            ("property", "Property"),
                            ("income_loss", "Income Loss"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the claim event (minimum 50 characters)",
                        validators=[django.core.validators.MinLengthValidator(50)],
                    ),
                ),
                ("documents", models.JSONField(default=list)),
                ("ai_verification", models.JSONField(blank=True, null=True)),
                ("ai_flagged", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("info_requested", "Info Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="submitted",
                        max_length=25,
                    ),
                ),
                ("decision_reason", models.TextField(blank=True)),
                ("payout_mpesa_ref", models.CharField(blank=True, max_length=30)),
                ("blockchain_hash", models.CharField(blank=True, max_length=66)),
                ("blockchain_tx", models.CharField(blank=True, max_length=66)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "claims_claim",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
