# Generated by Django 5.0.1 on 2026-04-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claims", "0001_initial"),
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="plan_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="plans.insuranceplan"
            ),
        ),
    ]
