# Generated by Django 5.0.1 on 2026-04-21 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("claims", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["user_id", "status"], name="claims_clai_user_id_127747_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(fields=["status"], name="claims_clai_status_b4f911_idx"),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["ai_flagged"], name="claims_clai_ai_flag_7170c1_idx"
            ),
        ),
    ]
