# Generated by Django 5.0.1 on 2026-04-21 17:04

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chama",
            fields=[
                (
                    "chama_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(max_length=200)),
                ("registration_no", models.CharField(max_length=50, unique=True)),
                (
                    "expected_members",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("dissolved", "Dissolved"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chamas_chama",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChamaMember",
            fields=[
                (
                    "membership_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "member_role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("left", "Left")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "chamas_chamember",
                "ordering": ["joined_at"],
            },
        ),
    ]
