# Generated by Django 5.0.1 on 2026-04-21 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chamas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chama",
            name="admin_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chamas_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chamamember",
            name="chama_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="chamas.chama",
            ),
        ),
        migrations.AddField(
            model_name="chamamember",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chama_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chama",
            index=models.Index(fields=["status"], name="chamas_cham_status_49b92f_idx"),
        ),
        migrations.AddIndex(
            model_name="chama",
            index=models.Index(
                fields=["admin_id"], name="chamas_cham_admin_i_e3000d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chamamember",
            index=models.Index(
                fields=["chama_id", "status"], name="chamas_cham_chama_i_0b18f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chamamember",
            index=models.Index(
                fields=["user_id"], name="chamas_cham_user_id_ef2632_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chamamember",
            unique_together={("chama_id", "user_id")},
        ),
    ]
